import type { NextPage } from 'next';
import Head from 'next/head';

import Header from '../../components/Header';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Joan Romero</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div className="mx-auto max-w-sm  px-4 sm:max-w-xl md:max-w-2xl lg:max-w-4xl xl:max-w-6xl">
				<p>hola</p>
			</div>
		</div>
	);
};

export default Home;
